# 090
# 다음 코드에서 에러가 발생한 원인을 설명하라.

# >> icecream = {'폴라포': 1200, '빵빠레': 1800, '월드콘': 1500, '메로나': 1000}
# >> icecream['누가바']
# Traceback(most recent call last):
#   File "<pyshell#69>", line 1, in <module >
#   icecream['누가바']
# KeyError: '누가바'

# 누가바가 딕셔너리의 원소로 들어가있지않다.
